services:
  backend:
    build: ./backend
    container_name: bchem-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: deno run --allow-net --allow-read src/main.ts
  test:
    build: .
    container_name: bchem-backend-tests
    command: ["deno", "test", "--allow-read"]
    volumes:
      - ./tests:/app/tests  
      - ./src:/app/src  
